# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcs/servers/converter.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'grpcs/servers/converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgrpcs/servers/converter.proto\x12\x03rag\">\n\x15ImageConverterRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x14\n\x0ctargetFormat\x18\x02 \x01(\t\")\n\x16ImageConverterResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32V\n\tConverter\x12I\n\x0c\x63onvertImage\x12\x1a.rag.ImageConverterRequest\x1a\x1b.rag.ImageConverterResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcs.servers.converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGECONVERTERREQUEST']._serialized_start=38
  _globals['_IMAGECONVERTERREQUEST']._serialized_end=100
  _globals['_IMAGECONVERTERRESPONSE']._serialized_start=102
  _globals['_IMAGECONVERTERRESPONSE']._serialized_end=143
  _globals['_CONVERTER']._serialized_start=145
  _globals['_CONVERTER']._serialized_end=231
# @@protoc_insertion_point(module_scope)
