# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpcs.servers import extractor_pb2 as grpcs_dot_servers_dot_extractor__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpcs/servers/extractor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExtractorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pdf2Text = channel.unary_unary(
                '/rag.Extractor/pdf2Text',
                request_serializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.SerializeToString,
                response_deserializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.FromString,
                _registered_method=True)
        self.word2Text = channel.unary_unary(
                '/rag.Extractor/word2Text',
                request_serializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.SerializeToString,
                response_deserializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.FromString,
                _registered_method=True)
        self.excel2Text = channel.unary_unary(
                '/rag.Extractor/excel2Text',
                request_serializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.SerializeToString,
                response_deserializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.FromString,
                _registered_method=True)
        self.html2Text = channel.unary_unary(
                '/rag.Extractor/html2Text',
                request_serializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.SerializeToString,
                response_deserializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.FromString,
                _registered_method=True)


class ExtractorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def pdf2Text(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def word2Text(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def excel2Text(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def html2Text(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtractorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'pdf2Text': grpc.unary_unary_rpc_method_handler(
                    servicer.pdf2Text,
                    request_deserializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.FromString,
                    response_serializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.SerializeToString,
            ),
            'word2Text': grpc.unary_unary_rpc_method_handler(
                    servicer.word2Text,
                    request_deserializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.FromString,
                    response_serializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.SerializeToString,
            ),
            'excel2Text': grpc.unary_unary_rpc_method_handler(
                    servicer.excel2Text,
                    request_deserializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.FromString,
                    response_serializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.SerializeToString,
            ),
            'html2Text': grpc.unary_unary_rpc_method_handler(
                    servicer.html2Text,
                    request_deserializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.FromString,
                    response_serializer=grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.Extractor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.Extractor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Extractor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def pdf2Text(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.Extractor/pdf2Text',
            grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.SerializeToString,
            grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def word2Text(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.Extractor/word2Text',
            grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.SerializeToString,
            grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def excel2Text(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.Extractor/excel2Text',
            grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.SerializeToString,
            grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def html2Text(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.Extractor/html2Text',
            grpcs_dot_servers_dot_extractor__pb2.TextExtractorRequest.SerializeToString,
            grpcs_dot_servers_dot_extractor__pb2.TextExtractorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
