# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcs/servers/nlp_analyzer.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'grpcs/servers/nlp_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n grpcs/servers/nlp_analyzer.proto\x12\x03rag\"-\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"0\n\rSentsResponse\x12\r\n\x05sents\x18\x01 \x03(\t\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t2C\n\x0bNlpAnalyzer\x12\x34\n\ntext2Sents\x12\x10.rag.TextRequest\x1a\x12.rag.SentsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcs.servers.nlp_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=41
  _globals['_TEXTREQUEST']._serialized_end=86
  _globals['_SENTSRESPONSE']._serialized_start=88
  _globals['_SENTSRESPONSE']._serialized_end=136
  _globals['_NLPANALYZER']._serialized_start=138
  _globals['_NLPANALYZER']._serialized_end=205
# @@protoc_insertion_point(module_scope)
