# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpcs.servers import nlp_analyzer_pb2 as grpcs_dot_servers_dot_nlp__analyzer__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpcs/servers/nlp_analyzer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NlpAnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.text2Sents = channel.unary_unary(
                '/rag.NlpAnalyzer/text2Sents',
                request_serializer=grpcs_dot_servers_dot_nlp__analyzer__pb2.TextRequest.SerializeToString,
                response_deserializer=grpcs_dot_servers_dot_nlp__analyzer__pb2.SentsResponse.FromString,
                _registered_method=True)


class NlpAnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def text2Sents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NlpAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'text2Sents': grpc.unary_unary_rpc_method_handler(
                    servicer.text2Sents,
                    request_deserializer=grpcs_dot_servers_dot_nlp__analyzer__pb2.TextRequest.FromString,
                    response_serializer=grpcs_dot_servers_dot_nlp__analyzer__pb2.SentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.NlpAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.NlpAnalyzer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NlpAnalyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def text2Sents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.NlpAnalyzer/text2Sents',
            grpcs_dot_servers_dot_nlp__analyzer__pb2.TextRequest.SerializeToString,
            grpcs_dot_servers_dot_nlp__analyzer__pb2.SentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
